# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

filter_centroids <- function(ms2ch, ms2mz, ms2rt, ms1, mz_tol, rt_range) {
    .Call('_oxiquant_filter_centroids', PACKAGE = 'oxiquant', ms2ch, ms2mz, ms2rt, ms1, mz_tol, rt_range)
}

